apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: food_traceability
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  OLLAMA_INTERNAL_URL: 'http://ollama:11434'
  OLLAMA_MODEL: 'llama2'
  BACKEND_INTERNAL_URL: 'http://backend:3000'
  NEXT_PUBLIC_API_URL: 'http://localhost:30000'
